# Read the documentation: https://core-bundle.leapt.io/configuration_reference.html
leapt_core:
    upload_dir: '%kernel.project_dir%/public'
    recaptcha:
        public_key:  '%env(RECAPTCHA_PUBLIC_KEY)%'
        private_key: '%env(RECAPTCHA_PRIVATE_KEY)%'

when@test:
    leapt_core:
        recaptcha:
            enabled: false
