twig:
    file_name_pattern: '*.twig'
    form_themes:
        - '@LeaptSlugType/bootstrap4_layout.html.twig'
        - '@LeaptCore/Form/bootstrap_4_layout.html.twig'
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
        - 'bootstrap_4_layout.html.twig'

when@test:
    twig:
        strict_variables: true
