twig:
    file_name_pattern: '*.twig'
    form_themes:
        - '@LeaptCore/Form/bootstrap_4_layout.html.twig'
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
        - 'form/form_layout.html.twig'

when@test:
    twig:
        strict_variables: true
